### ISSUE TITLE
credentials should default to false

### ISSUE THREAD

**Issue by acoshift** [SaltyAom/kingworld-cors#1]
Because

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
```

is invalid by [fetch spec](https://fetch.spec.whatwg.org/#cors-protocol-and-credentials) (section 3.2.5).

IMO, user must config `origin` and manually change `credentials` to true.

**Comment by SaltyAom** [comment]
Thanks, at the day I created this I surf a lot of RFC specs, and I think I forgot this one.
Here's fixed at [#7629c47](https://github.com/SaltyAom/kingworld-cors/commit/7629c47a870dc3868d97629b1ea0792079ed1988), and published as `0.0.0-experimental.1`
